name: Brigade Windows Go Tools Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: windows-2019
    env:
      DOCKER_ORG: brigadecore
    steps:
      - uses: actions/checkout@main
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Windows Go Tools
        run: $env:VERSION=$env:GITHUB_REF.substring(10, $env:GITHUB_REF.length-10); make push
